// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zfvnjdtajjdlqbjjzavh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpmdm5qZHRhampkbHFiamp6YXZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcxNzI1NzYsImV4cCI6MjA1Mjc0ODU3Nn0.6I8-2yiILPzgfBcJ2vEKlxApf22Ckom21kZFwABT7s8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);